spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://sideproject.ckq9ojvvxuo5.ap-northeast-2.rds.amazonaws.com:3306/umtDB
    username: admin
    password: 12341234
    driverClassName: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
